name: vishwanishastri/datastructure_and_algorithm_using_python
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python-version: [3.8]
    steps:
      - name: Checkout the repository source code
        uses: actions/checkout@v2
      - run: python linkedlist.py